version: 1.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
build_script:
- ps: dotnet restore
- ps: dotnet test Pagination.Tests/Pagination.Tests.csproj
- ps: dotnet pack Pagination/Pagination.csproj -c Release --include-symbols /p:Version=$($Env:APPVEYOR_BUILD_VERSION)
artifacts:
  - path: 'Pagination\**\*.nupkg'